package com.proficiency.db;

import com.proficiency.bean.resp.SpecificBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig specificBeanDaoConfig;

    private final SpecificBeanDao specificBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        specificBeanDaoConfig = daoConfigMap.get(SpecificBeanDao.class).clone();
        specificBeanDaoConfig.initIdentityScope(type);

        specificBeanDao = new SpecificBeanDao(specificBeanDaoConfig, this);

        registerDao(SpecificBean.class, specificBeanDao);
    }
    
    public void clear() {
        specificBeanDaoConfig.clearIdentityScope();
    }

    public SpecificBeanDao getSpecificBeanDao() {
        return specificBeanDao;
    }

}
